# vi:syntax=python
from typing import Any, Dict, List, Iterator, Optional

#def __getattr__(name : str) -> Any: ...

class Element:
  attrib: Dict[str, str]
  text: str
  tag: str
  def findall(self, q : str) -> List[Element]: ...
  def find(self, q : str) -> Optional[Element]: ...
  def __iter__(self) -> Iterator[Element]: ...

class ElementTree:
  def getroot(self) -> Element: ...

def parse(s : str) -> ElementTree: ...
